export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILED = "GET_CATEGORIES_FAILED";

export const GET_CURRENCIES = "GET_CURRENCIES";
export const GET_CURRENCIES_SUCCESS = "GET_CURRENCIES_SUCCESS";
export const GET_CURRENCIES_FAILED = "GET_CURRENCIES_FAILED";
export const SET_CURRENCY_TYPE = "SET_CURRENCY_TYPE";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAILED = "GET_PRODUCT_DETAILS_FAILED";

export const GET_ALL = "GET_ALL_PRODUCTS";
export const GET_ALL_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_FAILED = "GET_ALL_PRODUCTS_FAILED";

export const GET_TECH = "GET_TECH_PRODUCTS";
export const GET_TECH_SUCCESS = "GET_TECH_PRODUCTS_SUCCESS";
export const GET_TECH_FAILED = "GET_TECH_PRODUCTS_FAILED";

export const GET_CLOTHES = "GET_CLOTHES_PRODUCTS";
export const GET_CLOTHES_SUCCESS = "GET_CLOTHES_PRODUCTS_SUCCESS";
export const GET_CLOTHES_FAILED = "GET_CLOTHES_PRODUCTS_FAILED";

export const SET_PRODUCT_ATTRIBUTES = "SET_PRODUCT_ATTRIBUTES";
export const RESET_PRODUCT_ATTRIBUTES = "RESET_PRODUCT_ATTRIBUTES";

export const ADD_CART_ITEM = "ADD_CART_ITEM";
export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const ADD_CART_PRODUCT_DETAILS = "ADD_CART_PRODUCT_DETAILS";
export const ADD_CART_PRODUCT_DETAILS_SUCCESS = "ADD_CART_PRODUCT_DETAILS_SUCCESS";
export const ADD_CART_PRODUCT_DETAILS_FAILED = "ADD_CART_PRODUCT_DETAILS_FAILED";


